"""Build an offline reading edition from the repository-ready Markdown sources."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
pages=[('index','README','课程导览'),('chapter4','04_第一型积分_教程','第4章 · 第一型'),('chapter5','05_第二型积分_教程','第5章 · 第二型'),('review','06_期末题型与复习路线','真题与复习'),('sources','资料依据与覆盖对照','资料依据')]
links={stem+'.md':slug+'.html' for slug,stem,title in pages}
links['https://goya4140.github.io/JLU_CS_Course/2_1%E5%BE%AE%E7%A7%AF%E5%88%86III/index.html']='index.html'
style='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f5f7fa;color:#20333f;font-family:-apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif;line-height:1.85;font-size:17px}.top{background:#153c49;color:white;padding:22px 28px}.top strong{font-size:23px}.top p{margin:4px 0;color:#cfdee3;font-size:14px}.layout{max-width:1450px;margin:auto;display:grid;grid-template-columns:240px minmax(0,980px);gap:28px;padding:28px}.nav{position:sticky;top:20px;align-self:start;max-height:calc(100vh - 40px);overflow:auto;padding:15px 9px}.nav a{display:block;color:#41616d;text-decoration:none;padding:8px 12px;border-radius:7px;font-size:15px}.nav a.active{background:#dceef0;color:#145b67;font-weight:bold}.nav .label{font-size:12px;color:#69808a;letter-spacing:2px;margin:18px 12px 8px}.nav #toc a{font-size:13px;line-height:1.6;padding:6px 12px}main{min-width:0;background:white;padding:38px 48px;border-radius:14px;border:1px solid #e0e8ec;box-shadow:0 5px 20px #193c4910}h1{font-size:32px;line-height:1.4;margin:0 0 26px}h2{font-size:25px;margin:42px 0 16px;border-top:1px solid #e3eaed;padding-top:28px;scroll-margin-top:25px}h3{font-size:20px;margin:26px 0 12px;scroll-margin-top:25px}p{margin:15px 0}a{color:#117685;text-underline-offset:3px}blockquote{margin:22px 0;background:#eef7f7;border-left:4px solid #248b95;padding:8px 18px;color:#3c5962}figure{margin:25px 0;overflow-x:auto}figure figcaption{font-size:12px;color:#617984;text-align:center}img{display:block;width:100%;height:auto;margin:25px auto;border-radius:10px}table{border-collapse:collapse;width:100%;font-size:15px;line-height:1.65;margin:22px 0}th,td{text-align:left;border:1px solid #dce5ea;padding:12px 14px}th{background:#edf4f6}tr:nth-child(even){background:#f9fbfc}code{background:#edf3f5;border-radius:4px;padding:2px 5px;font-size:14px}pre{overflow:auto;background:#edf3f5;padding:15px}li{margin:8px 0}.katex-display{padding:12px 0;overflow-x:auto;overflow-y:hidden}.katex{font-size:1.05em}.foot{display:flex;justify-content:space-between;gap:20px;border-top:1px solid #e3eaed;margin-top:45px;padding-top:25px;font-size:15px}.error{background:#fee;color:#a00;padding:12px}footer{text-align:center;font-size:12px;color:#6f838d;padding:25px}@media(max-width:900px){.layout{display:block;padding:14px}.nav{position:static;max-height:none;display:flex;flex-wrap:wrap;gap:4px;padding:5px 0 14px}.nav .label,.nav #toc{display:none}.nav a{font-size:14px;padding:7px 10px}main{padding:26px 24px}figure img{min-width:650px}h1{font-size:27px}h2{font-size:23px}.top{padding:17px 22px}table{display:block;overflow-x:auto}}@media print{.top,.nav,.foot,footer{display:none}.layout{display:block;padding:0}body{background:white;font-size:11pt}main{border:0;padding:0;box-shadow:none}h2,h3{break-after:avoid}img,blockquote,tr{break-inside:avoid}.katex-display{overflow:visible}}'''
script=r'''const data=JSON.parse(document.getElementById('data').textContent);const maths=[];const tokenized=data.markdown.replace(/\$\$([\s\S]*?)\$\$|\$([^$\n]+)\$/g,(whole,block,inline)=>{let id=maths.length;maths.push({math:block??inline,display:block!==undefined});return `MATHPLACEHOLDER${id}END`;});let rendered=marked.parse(tokenized);rendered=rendered.replace(/MATHPLACEHOLDER(\d+)END/g,(_,id)=>{const m=maths[Number(id)];try{return katex.renderToString(m.math,{displayMode:m.display,throwOnError:true,strict:'warn'});}catch(e){return `<span class="error">公式错误：${e.message}</span>`;}});const content=document.getElementById('content');content.innerHTML=rendered;content.querySelectorAll('a').forEach(a=>{const original=a.getAttribute('href');if(data.links[original])a.href=data.links[original];});content.querySelectorAll('img').forEach(img=>{const figure=document.createElement('figure');img.before(figure);figure.append(img);const cap=document.createElement('figcaption');cap.textContent=img.alt+'（窄屏可横向滑动）';figure.append(cap);});content.querySelectorAll('h2,h3').forEach((h,i)=>{h.id='section-'+i;if(h.tagName==='H2'){let a=document.createElement('a');a.href='#'+h.id;a.textContent=h.textContent;document.getElementById('toc').append(a);}});window.__readingReady=true;'''
for i,(slug,stem,title) in enumerate(pages):
 data=json.dumps({'markdown':(ROOT/(stem+'.md')).read_text(),'links':links},ensure_ascii=False).replace('<','\\u003c')
 nav=''.join(f'<a class="{"active" if slug==s else ""}" href="{s}.html">{t}</a>' for s,m,t in pages)
 prev=f'<a href="{pages[i-1][0]}.html">← {pages[i-1][2]}</a>' if i else '<span></span>'
 nxt=f'<a href="{pages[i+1][0]}.html">{pages[i+1][2]} →</a>' if i+1<len(pages) else '<span></span>'
 doc=f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} | 微积分 III 图文教程</title><link rel="stylesheet" href="assets/vendor/katex.css"><style>{style}</style></head><body><header class="top"><a href="../#/" style="color:#cfdee3;text-decoration:none;font-size:14px">JLU CS Course / 大二上</a><br><strong>微积分 III · 图文教程</strong><p>理解概念 · 看懂图形 · 写出解题过程　/　第一版 · 前两章</p></header><div class="layout"><aside class="nav" aria-label="章节导航"><div class="label">课程内容</div>{nav}<div class="label">本页目录</div><nav id="toc"></nav></aside><main><article id="content"></article><div class="foot">{prev}{nxt}</div></main></div><footer>Markdown 内容源与 HTML 阅读版同步生成 · 本地公式和图片资源 · JLU CS Course</footer><script type="application/json" id="data">{data}</script><script src="assets/vendor/marked.js"></script><script src="assets/vendor/katex.js"></script><script>{script}</script></body></html>'''
 (ROOT/(slug+'.html')).write_text(doc)
print('Built',len(pages),'offline pages')
